### ISSUE TITLE
Update to use Build Service v2 API endpoint

### ISSUE THREAD

**Issue by onishiweb** [Financial-Times/next-flags-ui#22]
At the lines below please update to use the v2 API endpoint `build.origami.ft.com/v2/bundles`

https://github.com/Financial-Times/next-flags-ui/blob/5ba0a66aa232ceafa3b9f227e10e1224e1afcd21/views/flags-ui.html#L4

https://github.com/Financial-Times/next-flags-ui/blob/5ba0a66aa232ceafa3b9f227e10e1224e1afcd21/views/flags-ui.html#L59

**Comment by matthew-andrews** [comment]
i think we should just power down this app, i don't think it works anymore

**Comment by adambraimbridge** [comment]
I'm going to fix this app and power it up again, because now we have a need for it.
